
project_id = "lovable-dev-project"
app_version = "0.1.0"

[api.config]
port = 54321

[functions.search-with-attachments]
verify_jwt = false

[functions.search-with-attachments.environment_variables]
OPENAI_API_KEY = "sk-placeholder"
SUPABASE_URL = "YOUR_SUPABASE_URL"
SUPABASE_SERVICE_ROLE_KEY = "YOUR_SUPABASE_SERVICE_ROLE_KEY"
