// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmfhetqfewbjwqyoxqkd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tZmhldHFmZXdiandxeW94cWtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0ODUyMTUsImV4cCI6MjA1NTA2MTIxNX0.079LL235eAwSjjesZTarMnrLmFpmZdmzSAoiQO35XLI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);